"""Static checks on the browser assets.

These exist because of a bug that shipped and stayed shipped: topology.js
called ``buildDataUrl()`` without importing it, so the map silently failed
to load in every browser for several releases. Nothing caught it — the
jsdom harness concatenates page-utils.js and the page script into one
scope, which makes a missing import resolve just fine.

A parser would be better than regexes, but this project has no JS
toolchain and these checks only need to answer three blunt questions:

- does a page use something from page-utils without importing it?
- does a page import something that no longer exists?
- do the files the HTML references actually exist?
"""

import re
from pathlib import Path

import pytest

WEB = Path(__file__).resolve().parents[2] / "web"
JS_DIR = WEB / "assets" / "js"
PAGE_UTILS = JS_DIR / "page-utils.js"

PAGE_SCRIPTS = sorted(p for p in JS_DIR.glob("*.js") if p.name != "page-utils.js")

IMPORT_RE = re.compile(r'import\s*\{([^}]*)\}\s*from\s*"\./page-utils\.js";')


def exported_names() -> set:
    return set(re.findall(r"^export const (\w+)", PAGE_UTILS.read_text(), re.M))


def imported_names(source: str) -> set:
    match = IMPORT_RE.search(source)
    if not match:
        return set()
    return {name.strip() for name in match.group(1).split(",") if name.strip()}


def locally_declared(source: str) -> set:
    """Names the file defines itself, which shadow anything importable."""
    return set(
        re.findall(r"^\s*(?:const|let|var)\s+(\w+)\s*=", source, re.M)
    ) | set(re.findall(r"^\s*function\s+(\w+)\s*\(", source, re.M))


def called_names(source: str, candidates: set) -> set:
    body = source[IMPORT_RE.search(source).end():] if IMPORT_RE.search(source) else source
    return {name for name in candidates if re.search(rf"\b{name}\s*\(", body)}


@pytest.mark.parametrize("script", PAGE_SCRIPTS, ids=lambda p: p.name)
class TestPageScripts:
    def test_uses_nothing_it_did_not_import(self, script):
        source = script.read_text()
        exports = exported_names()
        used = called_names(source, exports)
        available = imported_names(source) | locally_declared(source)
        missing = used - available
        assert not missing, (
            f"{script.name} calls {sorted(missing)} from page-utils.js without "
            f"importing it — this throws a ReferenceError in the browser"
        )

    def test_imports_nothing_that_no_longer_exists(self, script):
        stale = imported_names(script.read_text()) - exported_names()
        assert not stale, f"{script.name} imports {sorted(stale)}, which page-utils.js no longer exports"

    def test_imports_are_actually_used(self, script):
        """Unused imports are usually a rename that half-landed."""
        source = script.read_text()
        imported = imported_names(source)
        # An import may be referenced without being called (passed as a
        # callback, say), so look for the bare identifier too.
        body = source[IMPORT_RE.search(source).end():] if IMPORT_RE.search(source) else source
        unused = {name for name in imported if not re.search(rf"\b{name}\b", body)}
        assert not unused, f"{script.name} imports {sorted(unused)} without using them"


class TestPages:
    @pytest.mark.parametrize(
        "page", sorted(WEB.glob("*.html")), ids=lambda p: p.name
    )
    def test_referenced_assets_exist(self, page):
        """Every local script, stylesheet, and image the page names is present."""
        source = page.read_text()
        refs = re.findall(r'(?:src|href)="([^"]+)"', source)
        missing = []
        for ref in refs:
            if ref.startswith(("http", "#", "//", "mailto:")):
                continue
            if ref in {"app-config.js"}:  # generated by the server, not a file
                continue
            if not (WEB / ref).exists():
                missing.append(ref)
        assert not missing, f"{page.name} references missing files: {missing}"


class TestBundledData:
    def test_basemap_is_present_and_shaped_correctly(self):
        """The topology map needs this file; losing it fails silently."""
        import json

        basemap = WEB / "assets" / "data" / "us-states.json"
        assert basemap.exists(), "the topology map outline is missing"
        data = json.loads(basemap.read_text())
        assert data["states"], "no state boundaries in the outline"
        assert data["country"], "no national outline (the coastline stroke)"
        for state in data["states"]:
            assert state["n"] and state["r"], f"malformed entry: {state}"
        # Small enough to bundle, which is the whole point of bundling it.
        assert basemap.stat().st_size < 200_000
