"""Static checks on the browser assets.

These exist because of a bug that shipped and stayed shipped: topology.js
called ``buildDataUrl()`` without importing it, so the map silently failed
to load in every browser for several releases. Nothing caught it — the
jsdom harness concatenates page-utils.js and the page script into one
scope, which makes a missing import resolve just fine.

A parser would be better than regexes, but this project has no JS
toolchain and these checks only need to answer three blunt questions:

- does a page use something from page-utils without importing it?
- does a page import something that no longer exists?
- do the files the HTML references actually exist?
"""

import re
from pathlib import Path

import pytest

WEB = Path(__file__).resolve().parents[2] / "web"
JS_DIR = WEB / "assets" / "js"
PAGE_UTILS = JS_DIR / "page-utils.js"

PAGE_SCRIPTS = sorted(p for p in JS_DIR.glob("*.js") if p.name != "page-utils.js")

IMPORT_RE = re.compile(r'import\s*\{([^}]*)\}\s*from\s*"\./page-utils\.js";')


def exported_names() -> set:
    return set(re.findall(r"^export const (\w+)", PAGE_UTILS.read_text(), re.M))


def imported_names(source: str) -> set:
    match = IMPORT_RE.search(source)
    if not match:
        return set()
    return {name.strip() for name in match.group(1).split(",") if name.strip()}


def locally_declared(source: str) -> set:
    """Names the file defines itself, which shadow anything importable."""
    return set(
        re.findall(r"^\s*(?:const|let|var)\s+(\w+)\s*=", source, re.M)
    ) | set(re.findall(r"^\s*function\s+(\w+)\s*\(", source, re.M))


def called_names(source: str, candidates: set) -> set:
    body = source[IMPORT_RE.search(source).end():] if IMPORT_RE.search(source) else source
    return {name for name in candidates if re.search(rf"\b{name}\s*\(", body)}


@pytest.mark.parametrize("script", PAGE_SCRIPTS, ids=lambda p: p.name)
class TestPageScripts:
    def test_uses_nothing_it_did_not_import(self, script):
        source = script.read_text()
        exports = exported_names()
        used = called_names(source, exports)
        available = imported_names(source) | locally_declared(source)
        missing = used - available
        assert not missing, (
            f"{script.name} calls {sorted(missing)} from page-utils.js without "
            f"importing it — this throws a ReferenceError in the browser"
        )

    def test_imports_nothing_that_no_longer_exists(self, script):
        stale = imported_names(script.read_text()) - exported_names()
        assert not stale, f"{script.name} imports {sorted(stale)}, which page-utils.js no longer exports"

    def test_imports_are_actually_used(self, script):
        """Unused imports are usually a rename that half-landed."""
        source = script.read_text()
        imported = imported_names(source)
        # An import may be referenced without being called (passed as a
        # callback, say), so look for the bare identifier too.
        body = source[IMPORT_RE.search(source).end():] if IMPORT_RE.search(source) else source
        unused = {name for name in imported if not re.search(rf"\b{name}\b", body)}
        assert not unused, f"{script.name} imports {sorted(unused)} without using them"


class TestPages:
    @pytest.mark.parametrize(
        "page", sorted(WEB.glob("*.html")), ids=lambda p: p.name
    )
    def test_referenced_assets_exist(self, page):
        """Every local script, stylesheet, and image the page names is present."""
        source = page.read_text()
        refs = re.findall(r'(?:src|href)="([^"]+)"', source)
        missing = []
        for ref in refs:
            if ref.startswith(("http", "#", "//", "mailto:")):
                continue
            if ref in {"app-config.js"}:  # generated by the server, not a file
                continue
            if not (WEB / ref).exists():
                missing.append(ref)
        assert not missing, f"{page.name} references missing files: {missing}"


class TestStylesheet:
    """A typo in a custom property drops the whole declaration, silently.

    ``padding: var(--space-4) var(--space-5)`` with no --space-5 defined
    does not fall back to something sensible — the browser throws the
    padding away entirely, and the only symptom is a cramped layout.
    """

    def test_every_custom_property_used_is_defined(self):
        css = (WEB / "assets" / "css" / "styles.css").read_text()
        defined = set(re.findall(r"^\s*(--[\w-]+)\s*:", css, re.M))
        # var(--x, fallback) is fine even when --x is absent; those are
        # written deliberately, so only flag the single-argument form.
        used = set(re.findall(r"var\(\s*(--[\w-]+)\s*\)", css))
        undefined = sorted(used - defined)
        assert not undefined, f"styles.css uses undefined custom properties: {undefined}"

    def test_javascript_only_sets_properties_that_exist(self):
        """JS reads theme colours by name; a rename would break them quietly."""
        css = (WEB / "assets" / "css" / "styles.css").read_text()
        defined = set(re.findall(r"^\s*(--[\w-]+)\s*:", css, re.M))
        for script in PAGE_SCRIPTS:
            used = set(re.findall(r'getPropertyValue\(\s*"(--[\w-]+)"', script.read_text()))
            undefined = sorted(used - defined)
            assert not undefined, f"{script.name} reads undefined properties: {undefined}"


class TestTopologyDefaultScope:
    """The topology opens on live connections only.

    A graph full of machines nobody at this deployment has a session to
    reads as noise — several are systems a given user has never heard of.
    But a status-page-only fleet has no live sessions at all, and must not
    open on an empty canvas, so the default is conditional.
    """

    SOURCE = (JS_DIR / "topology.js").read_text()

    def test_the_default_is_decided_from_the_data(self):
        assert "const resolveDefaultScope" in self.SOURCE
        assert "connected > 0" in self.SOURCE, (
            "the default must depend on there being something connected"
        )

    def test_an_absent_url_parameter_is_not_off(self):
        """?connected=0 is off; no parameter at all means 'decide for me'."""
        assert 'connectedParam === null ? null' in self.SOURCE
        assert 'params.set("connected", "0")' in self.SOURCE, (
            "turning it off must survive a reload"
        )

    def test_the_filter_treats_undecided_as_show_everything(self):
        assert "connectedOnly === true && !node.connected" in self.SOURCE, (
            "a null (undecided) scope must not hide anything"
        )

    def test_it_says_what_it_is_hiding(self):
        assert "holds " in self.SOURCE and "Live connections only" in self.SOURCE


class TestApiPageBaseUrl:
    """The base URL panel advertises what callers append to."""

    SOURCE = (JS_DIR / "api.js").read_text()

    def test_an_empty_path_resolves_to_the_directory(self):
        """new URL("", ".../api.html") is api.html itself, not the base."""
        assert '|| "."' in self.SOURCE, (
            'an empty relative path must become "." or the panel advertises '
            "the page's own URL"
        )


class TestBundledData:
    def test_basemap_is_present_and_shaped_correctly(self):
        """The topology map needs this file; losing it fails silently."""
        import json

        basemap = WEB / "assets" / "data" / "us-states.json"
        assert basemap.exists(), "the topology map outline is missing"
        data = json.loads(basemap.read_text())
        assert data["states"], "no state boundaries in the outline"
        assert data["country"], "no national outline (the coastline stroke)"
        for state in data["states"]:
            assert state["n"] and state["r"], f"malformed entry: {state}"
        # Small enough to bundle, which is the whole point of bundling it.
        assert basemap.stat().st_size < 200_000
